### ISSUE TITLE
RFE: Install mongosh

### ISSUE THREAD

**Issue by FGasper** [aheckmann/m#86]
I expected this tool to install mongosh along with mongod & mongos, but that’s not what happens. The tools also don’t include the shell.

I can install it via other ways, but it’d be nice if this tool offered it, too.

Thanks for considering!

**Comment by stennie** [comment]
Hi @FGasper,

`mongosh` isn't included with the tarball/zip downloads used by `m`, so would have to be fetched separately. This is a reasonable enhancement suggestion, but will require some testing to confirm url patterns.

Since `mongosh`  works across all supported versions of MongoDB server, you could also install the binary once via alternative means and use this to connect to any of your deployments. 

Regards,
Stennie

**Comment by stennie** [comment]
Adding cross-platform installation support for `mongosh` seems overly involved given the dependency on Node.js.

However, I've added #95 as a convenience for macOS users since there is a `brew` package available.
